-- Table 1 : airfare_quotes
create table public.airfare_quotes (
  id bigint generated by default as identity not null,
  collected_at timestamp with time zone not null default now(),
  collection_date date not null,
  origin text not null,
  destination text not null,
  airline text not null,
  flight_number text not null,
  travel_date date not null,
  lead_time integer not null,
  departure_time timestamp with time zone null,
  arrival_time timestamp with time zone null,
  duration_minutes integer null,
  stops integer null,
  fare_class text null,
  fare_class_of_service text null,
  fare_code text null,
  product_class text null,
  base_fare numeric(12, 2) null,
  taxes numeric(12, 2) null,
  udf numeric(12, 2) null,
  fees numeric(12, 2) null,
  convenience_fee numeric(12, 2) null,
  service_fee numeric(12, 2) null,
  other_charges numeric(12, 2) null,
  total_fare numeric(12, 2) not null,
  currency text not null default 'INR'::text,
  availability integer null,
  source text not null,
  quote_key text not null,
  segments jsonb null,
  fee_breakdown jsonb null,
  breakdown_match boolean null,
  constraint airfare_quotes_pkey primary key (id),
  constraint airfare_quotes_destination_len check ((char_length(destination) = 3)),
  constraint airfare_quotes_lead_time_valid check ((lead_time >= 0)),
  constraint airfare_quotes_availability_valid check (
    (
      (availability is null)
      or (availability >= 0)
    )
  ),
  constraint airfare_quotes_stops_valid check (
    (
      (stops is null)
      or (stops >= 0)
    )
  ),
  constraint airfare_quotes_total_positive check ((total_fare > (0)::numeric)),
  constraint airfare_quotes_origin_len check ((char_length(origin) = 3))
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_airfare_quotes_collection_quote on public.airfare_quotes using btree (collection_date, quote_key) TABLESPACE pg_default;

create index IF not exists idx_airfare_quotes_route_collection on public.airfare_quotes using btree (origin, destination, collection_date) TABLESPACE pg_default;

create index IF not exists idx_airfare_quotes_route_travel on public.airfare_quotes using btree (origin, destination, travel_date) TABLESPACE pg_default;

create index IF not exists idx_airfare_quotes_route_lead_time on public.airfare_quotes using btree (origin, destination, lead_time) TABLESPACE pg_default;

create index IF not exists idx_airfare_quotes_airline on public.airfare_quotes using btree (airline) TABLESPACE pg_default;

create index IF not exists idx_airfare_quotes_source on public.airfare_quotes using btree (source) TABLESPACE pg_default;





-- Table 2 : apix_history
create table public.apix_history (
  id bigint generated by default as identity not null,
  index_date date not null,
  apix numeric(14, 4) not null,
  previous_apix numeric(14, 4) null,
  change_value numeric(14, 4) null,
  change_pct numeric(10, 4) null,
  baseline_date date null,
  calculation_version text not null default 'v1'::text,
  calculation_status text not null default 'calculated'::text,
  error_message text null,
  route_count_expected integer null,
  route_count_used integer null,
  weighted_route_count integer null,
  observation_count integer null,
  valid_breakdown_count integer null,
  breakdown_quality_pct numeric(7, 3) null,
  weight_coverage_pct numeric(7, 3) null,
  lead_times_expected jsonb null,
  routes_missing jsonb null,
  route_weights_snapshot jsonb null,
  source_coverage jsonb null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint apix_history_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_apix_history_index_date on public.apix_history using btree (index_date) TABLESPACE pg_default;

create index IF not exists idx_apix_history_date on public.apix_history using btree (index_date) TABLESPACE pg_default;

create index IF not exists idx_apix_history_baseline_date on public.apix_history using btree (baseline_date) TABLESPACE pg_default;



-- Table 3 : apix_leadtime_history
create table public.apix_leadtime_history (
  id bigint generated by default as identity not null,
  run_id uuid null,
  index_date date not null,
  origin text not null,
  destination text not null,
  lead_time integer not null,
  travel_date date not null,
  representative_total_fare numeric(14, 2) null,
  representative_base_fare numeric(14, 2) null,
  representative_taxes numeric(14, 2) null,
  representative_udf numeric(14, 2) null,
  representative_fees numeric(14, 2) null,
  representative_convenience_fee numeric(14, 2) null,
  representative_service_fee numeric(14, 2) null,
  representative_other_charges numeric(14, 2) null,
  quote_count integer null,
  flight_count integer null,
  journey_count integer null,
  airline_count integer null,
  breakdown_valid_count integer null,
  breakdown_quality_pct numeric(7, 3) null,
  source_coverage jsonb null,
  currency text null,
  created_at timestamp with time zone not null default now(),
  constraint apix_leadtime_history_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_apix_leadtime_history on public.apix_leadtime_history using btree (index_date, origin, destination, lead_time) TABLESPACE pg_default;

create index IF not exists idx_apix_leadtime_history_date on public.apix_leadtime_history using btree (index_date) TABLESPACE pg_default;

create index IF not exists idx_apix_leadtime_history_route on public.apix_leadtime_history using btree (origin, destination) TABLESPACE pg_default;

create index IF not exists idx_apix_leadtime_history_lead_time on public.apix_leadtime_history using btree (lead_time) TABLESPACE pg_default;




-- Table 4 : apix_route_history
create table public.apix_route_history (
  id bigint generated by default as identity not null,
  run_id uuid null,
  index_date date not null,
  baseline_date date null,
  origin text not null,
  destination text not null,
  route_weight numeric(10, 6) null,
  representative_total_fare numeric(14, 2) null,
  baseline_total_fare numeric(14, 2) null,
  route_index numeric(14, 4) null,
  fare_change numeric(14, 2) null,
  fare_change_pct numeric(10, 4) null,
  weighted_contribution numeric(14, 6) null,
  representative_base_fare numeric(14, 2) null,
  representative_taxes numeric(14, 2) null,
  representative_udf numeric(14, 2) null,
  representative_fees numeric(14, 2) null,
  representative_convenience_fee numeric(14, 2) null,
  representative_service_fee numeric(14, 2) null,
  representative_other_charges numeric(14, 2) null,
  baseline_base_fare numeric(14, 2) null,
  baseline_taxes numeric(14, 2) null,
  baseline_udf numeric(14, 2) null,
  baseline_fees numeric(14, 2) null,
  baseline_convenience_fee numeric(14, 2) null,
  baseline_service_fee numeric(14, 2) null,
  baseline_other_charges numeric(14, 2) null,
  base_fare_change numeric(14, 2) null,
  base_fare_change_pct numeric(10, 4) null,
  taxes_change numeric(14, 2) null,
  taxes_change_pct numeric(10, 4) null,
  udf_change numeric(14, 2) null,
  udf_change_pct numeric(10, 4) null,
  fees_change numeric(14, 2) null,
  fees_change_pct numeric(10, 4) null,
  convenience_fee_change numeric(14, 2) null,
  convenience_fee_change_pct numeric(10, 4) null,
  service_fee_change numeric(14, 2) null,
  service_fee_change_pct numeric(10, 4) null,
  other_charges_change numeric(14, 2) null,
  other_charges_change_pct numeric(10, 4) null,
  current_quote_count integer null,
  baseline_quote_count integer null,
  current_lead_times_observed integer null,
  baseline_lead_times_observed integer null,
  lead_time_coverage_pct numeric(7, 3) null,
  current_breakdown_quality_pct numeric(7, 3) null,
  baseline_breakdown_quality_pct numeric(7, 3) null,
  airline_count integer null,
  source_coverage jsonb null,
  currency text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint apix_route_history_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_apix_route_history_date_route on public.apix_route_history using btree (index_date, origin, destination) TABLESPACE pg_default;

create index IF not exists idx_apix_route_history_date on public.apix_route_history using btree (index_date) TABLESPACE pg_default;

create index IF not exists idx_apix_route_history_route on public.apix_route_history using btree (origin, destination) TABLESPACE pg_default;

create index IF not exists idx_apix_route_history_baseline on public.apix_route_history using btree (baseline_date) TABLESPACE pg_default;


create index IF not exists idx_airfare_quotes_quote_key on public.airfare_quotes using btree (quote_key) TABLESPACE pg_default;
